name: Remove label on close
on:
  issues:
    types: ['closed']

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://k8slt/github-labeler-action@sha256:059ccbafe84cbf8fab08211e14690b78b04b5cc8e95f2686f9cab53efb4a9586
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          default-labels: '["test-1"]'
