name: Labeling new issue
on:
  issues:
    types: ['reopened']
  issue_comment:
    types: ['created']
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@2fc6ce2
        if: github.event_name == 'issues' || ( github.event_name == 'issue_comment' && github.event.issue.state == 'closed')
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          default-labels: '["test-1"]'
