name: Checks after release is published
on:
  release:
    types: ['published']
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to check'
        required: true
jobs:
  validate-github-action:
    runs-on: ubuntu-latest
    steps:
      - uses: k14s/setup-k14s-action@v1
        with:
          only: ytt
      - run: |
          ytt version
          version=`ytt version`
          echo "ytt version == $version"
          v1=$($github.event.inputs.version || $GITHUB_REF)
          echo "actual version: $v1"
          release_version="$(echo $v1 | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/')"
          echo "release_version == $release_version"
          if [[ "${version}" == "$release_version" ]];
          then
            echo "Version match with latest"
            exit 0
          else
            echo "Versions do not match $version != $release_version"
            exit 1
          fi
